language:
  - node_js

node_js:
  - "6"
  - "5"
  - "4"

services:
  - postgresql

env:
  global:
    - SECRET_KEY=test
    - githubClientID=123456
    - githubClientSecret=123456
    - callbackURL=http://127.0.0.1:3000/auth/github/callback

before_script:
  - npm install -g istanbul

script:
  - npm test

after_script:
  - npm run coveralls

